title: "Machine Learning - Maestría en Ingeniería Biomédica"
author: "Andrés Duarte Chaves"
copyright: "2026"
repository:
  url: "https://github.com/aduartech81/MachineLearning"
html:
  baseurl: "/MachineLearning/"
execute:
  execute_notebooks: "off"
